### ISSUE TITLE
Implementazione interfaccia swing

### ISSUE THREAD

**Issue by RobertaConti-Jarvis** [irenedg/CRUD-uno#2]

**Comment by g-golia** [comment]
796247c8aa25bf56d1c5046e2790b1a95d6e3acd

**Comment by AulicinoDiego** [comment]
Commit : 1571477ca234999f034fbe040f8a1774d4b29176

**Comment by g-golia** [comment]
Sistemato funzionamento button con Commit: a957202b896bd0f899cf218b24081730d2c2754b
